version: "3.8"

services:
  issuer_coord:
    container_name: issuer_coord
    build: ./issuer_coord
    env_file:
      - ./issuer_coord/.env
      - ./vault-init/env/vault_approle.env
    environment:
      # Agregamos la variable de entorno para conectar a la nueva BBDD de issuer_coord
      MONGODB_URI: "mongodb://mongo-issuer_coord:27017/issuercoord?authSource=admin"
      # Si deseas añadir autenticación, puedes configurar usuario/contraseña en mongo-issuer_coord y en la URI.
    ports:
      - "5500:5500"
    networks:
      - my_network
    depends_on:
      - backend
      - mongo-issuer_coord   # Ahora depende también de su propia instancia de Mongo

  backend:
    container_name: backend
    build: ./backend
    environment:
      MONGO_URI: "mongodb://mongo-backend:27017/seguridadSocial"
    ports:
      - "3001:3001"
    networks:
      - my_network
    depends_on:
      - mongo-backend

  mongo-backend:
    container_name: mongo-backend
    image: mongo:5.0
    networks:
      - my_network

  # Nuevo servicio Mongo para issuer_coord
  mongo-issuer_coord:
    container_name: mongo-issuer_coord
    image: mongo:5.0
    # Opcionalmente, puedes agregar variables de entorno para usuario/contraseña
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my_network

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      REACT_APP_BACKEND_URL: "http://backend:3001"
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - backend

networks:
  my_network:
    external: true
    name: my_network
