FROM ubuntu:22.04

# Instalar dependencias para Vault
RUN apt-get update && apt-get install -y gpg wget curl jq unzip lsb-release ca-certificates gnupg

# Añadir keyring de HashiCorp
RUN wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list

RUN apt-get update && apt-get install -y vault

WORKDIR /work
